ADD StellarObject
Cryborg/Speedbots pull request #5
Opened 2021-01-09 01:37 UTC by Saromase

Ajout des objets d'un système stellaire.

La position n'est pas encore prise en compte.

2021-01-09 07:36 UTC, MartyFr requested changes

2021-01-09 07:36 UTC, MartyFr commented on app/Models/StellarObject.php
> +        'disapear_at'
Je pense qu'il faudrait caster tous les champs date dans les models

2021-01-09 07:36 UTC, MartyFr commented on app/Http/Controllers/StellarObjectController.php
> +     */
N'oublie pas les policies. Par défaut seuls les admins et le propriétaire de l'objet, s'il y en a un, peut créer, modifier ou supprimer.

2021-01-09 07:36 UTC, MartyFr commented on app/Http/Controllers/StellarObjectController.php
> +        return response()->json(StellarObject::get());
Attention, ici tu vas sortir la liste de tous les stellarObjecys en base. Il faut filtrer par StellarSystem.

2021-01-09 07:36 UTC, MartyFr commented on app/Http/Controllers/StellarObjectController.php
> +    public function show($id)
Il vaut mieux utiliser l'injection de dépendance ici, pour éviter d'avoir à faire un ::fond()
Ça permet aussi d'éviter à avoir à gérer la non-existence d'un model, ce sera fait par Laravel.
À faire dans tout le fichier

2021-01-09 07:36 UTC, MartyFr commented on database/migrations/2021_01_06_231631_create_stellar_objects_table.php
> +                ->comment('If stellar object have end time of appearance');
"If the stellar object is ephemeral"

2021-01-10 20:46 UTC, Saromase commented on app/Models/StellarObject.php
> +        'disapear_at'
OK

2021-01-10 21:23 UTC, Saromase commented on app/Http/Controllers/StellarObjectController.php
> +        return response()->json(StellarObject::get());
C'est corrigé, utilisation d'une route spécifique pour passer l'id du systeme ici

2021-01-10 21:48 UTC, merged